name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: mojispravy    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'MojiSpravy'      # set this to the path to your web app project
  DOTNET_VERSION: '9.0.x'           # set this to the .NET version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/MojiSpravy.csproj
    
    - name: Build
      run: dotnet build ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/MojiSpravy.csproj --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/MojiSpravy.csproj --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/MojiSpravy.csproj --configuration Release --output ${{ github.workspace }}/publish
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/publish 