name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  HEROKU_APP_NAME: mojispravy    # set this to your Heroku app name
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore MojiSpravy/MojiSpravy.csproj
    
    - name: Build
      run: dotnet build MojiSpravy/MojiSpravy.csproj --configuration Release --no-restore
    
    - name: Test
      run: dotnet test MojiSpravy/MojiSpravy.csproj --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish MojiSpravy/MojiSpravy.csproj --configuration Release --output ${{ github.workspace }}/publish
    
    - name: Create Procfile
      run: echo "web: dotnet MojiSpravy.dll" > ${{ github.workspace }}/publish/Procfile
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ env.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: ${{ github.workspace }}/publish
        procfile: "web: dotnet MojiSpravy.dll" 