name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: mojispravy    # set this to your Google Cloud project ID
  SERVICE_NAME: mojispravy  # set this to your Cloud Run service name
  REGION: europe-west1      # set this to your preferred region

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore MojiSpravy/MojiSpravy.csproj
    
    - name: Build
      run: dotnet build MojiSpravy/MojiSpravy.csproj --configuration Release --no-restore
    
    - name: Test
      run: dotnet test MojiSpravy/MojiSpravy.csproj --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish MojiSpravy/MojiSpravy.csproj --configuration Release --output ${{ github.workspace }}/publish
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Authorize Docker push
      run: gcloud auth configure-docker
    
    - name: Build and Push Container
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        flags: '--platform managed --allow-unauthenticated' 